language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

cache:
    directories:
        - $HOME/.cache

sudo: required

services:
  - docker
  - rabbitmq

compiler:
    - gcc

addons:
  apt:
    packages:
      # canvas
      - libgif-dev

before_install:
    # Fix a travis/boto issue.  See
    # https://github.com/travis-ci/travis-ci/issues/7940
    - sudo rm -f /etc/boto.cfg

    - GIRDER_VERSION=2.x-maintenance
    - GIRDER_WORKER_VERSION=master
    - main_path=$PWD
    - build_path=$PWD/build
    - mkdir -p $build_path

    - girder_path=$build_path/girder
    - rm -fr $girder_path
    - git clone https://github.com/girder/girder.git $girder_path && git -C $girder_path checkout $GIRDER_VERSION
    - ln -sf $main_path $girder_path/plugins/
    - ls -l $girder_path/plugins

    - girder_worker_path=$girder_path/plugins/girder_worker
    - git clone https://github.com/girder/girder_worker.git $girder_worker_path && git -C $girder_worker_path checkout $GIRDER_WORKER_VERSION
    - cp $PWD/plugin_tests/data/girder_worker.cfg $girder_worker_path/girder_worker/worker.local.cfg
    - pip install --no-cache-dir -U $girder_worker_path'[girder_io,docker]'

    - export MONGO_VERSION=3.2.18
    - export PY_COVG="ON"
    - CACHE=$HOME/.cache source $girder_path/scripts/install_mongo.sh
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version

    - CACHE=$HOME/.cache CMAKE_VERSION=3.1.0 CMAKE_SHORT_VERSION=3.1 source $girder_path/scripts/install_cmake.sh
    - cmake --version

    - mkdir -p $HOME/.cache/node_modules || true
    - ln -sf $HOME/.cache/node_modules .
    - npm install -g npm
    - npm --version
    - npm prune
    - npm install -g npm-install-retry

install:
    - pip install --upgrade 'git+https://github.com/cdeepakroy/ctk-cli'
    - cd $girder_path
    - pip install -r requirements-dev.txt -e .[worker]
    - pip install -r $main_path/requirements.txt
    - npm-install-retry
    - BABEL_ENV=cover girder-install web --plugins=slicer_cli_web,worker,jobs --dev

script:
    - cd $girder_worker_path
    - python2 -m girder_worker -l info >/tmp/worker.out 2>&1 &
    - mkdir -p $build_path/girder_testing_build
    - cd $build_path/girder_testing_build
    - cmake -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} -DPYTHON_COVERAGE_CONFIG="$main_path/plugin_tests/pycoverage.cfg" -DCOVERAGE_MINIMUM_PASS=19 -DJS_COVERAGE_MINIMUM_PASS=19 -DRUN_CORE_TESTS:BOOL="OFF" -DTEST_PLUGINS:STRING="slicer_cli_web" $girder_path
    - make
    - JASMINE_TIMEOUT=15000 ctest -VV

after_failure:
  # On failures, show the worker output and other information
  - pip freeze
  - cat /tmp/worker.out

after_success:
    - bash <(curl -s https://codecov.io/bash)
